version: '3.3'
services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'mySql2019'
      MYSQL_ROOT_PASSWORD: "mySql2019!"
      MYSQL_DATABASE: "agenda"
    ports:
      - "3307:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge